### ISSUE TITLE
publishing api's after changing the root-context of the apiman-gateway.war fails

### ISSUE THREAD

**Issue by nvdrk** [apiman/apiman#875] opened 2020-07-29 14:49 UTC
I am using apiman on docker. To change the gateway endpoint I changed the root context in jboss-web.xml from apiman-gateway
to apiv1 and repacked the .war, like you recommended. Now the APIs I created before are working with the new endpoint but I cannot publish new APIs. I am still using the gateway, gateway-api and elasticsearch that come with the image but I am using an external Keycloak instance.

```
io.apiman.manager.api.rest.contract.exceptions.ActionException: Failed to publish API.
	at io.apiman.manager.api.rest.impl.util.ExceptionFactory.actionException(ExceptionFactory.java:331)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.publishApi(ActionResourceImpl.java:230)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.performAction(ActionResourceImpl.java:105)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl$Proxy$_$$_WeldClientProxy.performAction(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:56)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.Exception: Api publishing failed: 308
	at io.apiman.manager.api.gateway.rest.GatewayClient.publish(GatewayClient.java:225)
	at io.apiman.manager.api.gateway.rest.RestGatewayLink.publishApi(RestGatewayLink.java:167)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.publishApi(ActionResourceImpl.java:204)
	... 80 more
Caused by: java.lang.Exception: Api publishing failed: 308
	at io.apiman.manager.api.gateway.rest.GatewayClient.publish(GatewayClient.java:220)
	... 82 more
```

**Comment by EricWittmann** [comment] 2020-07-30 13:52
IIRC there is an admin-only section of the Apiman UI that allows you to configure the Gateway link(s).  Have you updated the URL of the Gateway link in that UI?

**Comment by nvdrk** [comment] 2020-07-30 14:14
You mean the configuration endpoint? I tried with no luck (either 404 or 500). Do I have to change the apiman-gateway-api.war as well? Because from the information I found it seemed that changing the root-context of the apiman-gateway.war was sufficient to accomplish this. Sorry if wasn't clear enough.

**Comment by EricWittmann** [comment] 2020-07-31 17:31
Yes, I'm referring to this:

![image](https://user-images.githubusercontent.com/1890703/89060905-d0504080-d331-11ea-9add-1c7a35fed0a1.png)

![image](https://user-images.githubusercontent.com/1890703/89060938-de05c600-d331-11ea-9d08-acb92ba01726.png)

![image](https://user-images.githubusercontent.com/1890703/89060979-ee1da580-d331-11ea-88a1-beb39be7ce7f.png)

You need to update the Configuration Endpoint on that page.  Change that value and run "Test Gateway" - the result of doing that should be:

![image](https://user-images.githubusercontent.com/1890703/89061084-160d0900-d332-11ea-8400-5be070a3f831.png)

If that is the result you get, then everything is cool.  If you can't get that result then you'll need to provide more details for us to help. :)

**Comment by nvdrk** [comment] 2020-08-03 14:08
Even if I get this result I cannot publsih new apis. Inside the container there is a **apiman-gateway.war** and a **apiman-gateway-api.war**. All the resources I found online talked about changing the jboss-web.xml and repacking the **apiman-gateway.war**, which I did. I changed the root-context to _apiv1_ and it worked for all the apis that I already published.
Now, by just changing the **apiman-gateway.war** I wasn't able to sucessfully change the gateway endpoint like you showed and I also was not able to publish new apis.
When I additionally change the **apiman-gateway-api.war** in the same way, the test for the gateway configuration works with _apiv1_, but even then I am not able to publish new apis. Do I have make some additional modifications? what is the relationship between apiman-gateway and apiman-gateway-api? I hope this clears things up a bit. Appreciate your help!

**Comment by EricWittmann** [comment] 2020-08-03 16:54
Yes this helps very much, and I'm sorry to say I may have steered you wrong a bit here because this stuff is a bit old for me and I forgot about the two different WARs (gateway and gateway-api).  Now that you've refreshed my memory, it goes like this:

`apiman-gateway.war` - this WAR represent the actual runtime Gateway that clients will use when trying to make managed API calls (this is the WAR that applies the configured policies when clients try to access protected/managed APIs).  

`apiman-gateway-api.war` - this is a REST API to configure the Gateway itself.  This WAR is protected by authentication (auth is why we have two separate WARs).

So you will want to change `apiman-gateway.war` but leave `apiman-gateway-api.war` alone.  I think this is what you did originally.   So go back to that.  :)  No need to make any changes to `apiman-gateway-api.war`!!  And as a result, no need to make changes to that UI that I pointed you at before.  The URL to the **Gateway API** should stay the same.  It's only the URL to the **actualy Gateway** that you want to change.

Hopefully I now understand.

Looking at your error stack trace from your original comment, I wonder if perhaps the change to the gateway may be a bit of a red herring.  The root cause seems to indicate that the Gateway API call failed with a 308 HTTP response code.  That indicates a `Permanent Redirect` error.  Any idea why you'd get a 308 error from the Gateway API?  Can you try using postman or curl to hit the Gateway API's status endpoint at `$GATEWAY_ENDPOINT/system/status`?

**Comment by nvdrk** [comment] 2020-08-04 08:52
`$GATEWAY_ENDPOINT/system/status` results in "unauthorized" but I am now able to publish new apis. As you said the issue was not related to the changes I did to the gateway. I suspect the unauthorized indicates a different problem but at least the publishing works. Thank you very much for your help!

**Comment by EricWittmann** [comment] 2020-08-10 16:26
OK would love to know how you fixed it . But in any case if everything is working for you should we close this issue?

**Closed** 2020-08-12 20:02 UTC
Labels: question
