### ISSUE TITLE
can read the custom metrics index name in latest version 2.2.0

### ISSUE THREAD

**Issue by shachindrasingh** [apiman/apiman#1759] opened 2022-01-21 17:15 UTC
we can't define our own metrics index name in apiman version 2.2.0 .

**Comment by OSMOSA44** [comment] 2022-01-22 09:57
Hi, Probably a Duplicate of #1451

**Comment by msavy** [comment] 2022-01-22 17:31
Thanks @OSMOSA44 .

See #1451

**Closed by msavy** 2022-01-22 17:31 UTC
