### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by VEINHORN** [apiman/apiman#352] opened 2016-02-04 11:09 UTC
When I try to navigate to http://192.168.5.109:8080/apimanui apiman redirects to realm auth page but here I get message:

![we're sorry](http://i.imgur.com/R4BGQKq.png?1)

Logs:
`13:54:23,516 WARN  [org.keycloak.events] (default task-25) type=LOGIN_ERROR, realmId=apiman, clientId=apimanui, userId=null, ipAddress=10.57.31.102, error=invalid_redirect_uri, response_type=code, redirect_uri=http://192.168.5.109:8080/apimanui/, response_mode=query
`

**Comment by EricWittmann** [comment] 2016-02-04 12:14
In order to login using a URL other than localhost, you need to log into Keycloak and modify the list of valid redirect URLs.  Steps:

1. Login to keycloak here:  https://192.168.5.109:8443/auth
2. Credentials:   admin/admin123!
3. Switch to the "apiman" realm
4. Go to "Clients"
5. Edit the "apimanui" client
6. Add your IP address as one of the options for Valid Redirect URLs

**Comment by EricWittmann** [comment] 2016-02-04 13:42
Note that this is caused by a bug in Keycloak:

https://issues.jboss.org/browse/KEYCLOAK-2390

The bug will be fixed in the next release, which we will upgrade to whenever we can.  Once the bug is fixed we'll switch back to relative paths for our valid redirect URIs and this won't happen again!

**Closed by EricWittmann** 2016-02-04 13:42 UTC

**Comment by VEINHORN** [comment] 2016-02-04 14:13
@EricWittmann thank you. :+1:

**Comment by EricWittmann** [comment] 2016-02-04 14:23
You're quite welcome, and thanks for the :+1: emoji - that made me smile. :)
