### ISSUE TITLE
[Gateways][2.1.0] Unable to set different index metrics name for each gateway instance

### ISSUE THREAD

**Issue by OSMOSA44** [apiman/apiman#1451] opened 2021-08-17 12:55 UTC
Bonjour,

In our configuration, we have decided to create elasticsearch indices per gateway (more than 20 gateways)

With version 1.5.1, there was no problem with this configuration fixing `index` propertie for each component (snippet of relevant configuration below)

```xml
apiman.es.index=${env:APIMAN_GATEWAY_REGISTRY_CLIENT_INDEX}
apiman-gateway.registry.client.index=${apiman.es.index}_registry
apiman-gateway.metrics.client.index=${apiman.es.index}_metrics
apiman-gateway.components.ISharedStateComponent.client.index=${apiman.es.index}_share
apiman-gateway.components.IRateLimiterComponent.client.index=${apiman.es.index}_quota
apiman-gateway.components.ICacheStoreComponent.client.index=${apiman.es.index}_cache

```

With version 2.1.0, we want to keep the same configuration but `index` has been replaced by `indexPrefix` and the behaviour differs. With the configuration below

```bash
apiman.es.index=${env:APIMAN_GATEWAY_REGISTRY_CLIENT_INDEX}
apiman-gateway.registry.client.indexPrefix=${apiman.es.index}_registry
apiman-gateway.metrics.client.indexPrefix=${apiman.es.index}_metrics
apiman-gateway.components.ISharedStateComponent.client.indexPrefix=${apiman.es.index}_share
apiman-gateway.components.IRateLimiterComponent.client.indexPrefix=${apiman.es.index}_quota
apiman-gateway.components.ICacheStoreComponent.client.indexPrefix=${apiman.es.index}_cache
```

The first launch give us on elasticsearch those indices (with env APIMAN_GATEWAY_REGISTRY_CLIENT_INDEX=gw_test)

```bash
yellow open gw_test_metrics              ZnqEP2s0T5izK3lTY9drzg 1 1 0 0 208b 208b
yellow open gw_test_registry_apis        2AEQK4r7QVWJSYw7JE8zxw 1 1 0 0 208b 208b
yellow open gw_test_registry_clients     uNAjbeFxSOmTsPZdADmtVw 1 1 0 0 208b 208b
yellow open gw_test_registry_dataversion 9jpMxnsZQGWLNABGUvUPuw 1 1 0 0 208b 208b
```

On next step i declare a test api and request it, that generates a new `apiman_metrics` indice which will be global for all my gateway instances

```bash
yellow open apiman_metrics               uTWxXbqaQ0CSM7K5uDcp2Q 1 1 1 0 10.4kb 10.4kb
yellow open gw_test_metrics              ZnqEP2s0T5izK3lTY9drzg 1 1 0 0   208b   208b
yellow open gw_test_registry_apis        2AEQK4r7QVWJSYw7JE8zxw 1 1 1 0    7kb    7kb
yellow open gw_test_registry_clients     uNAjbeFxSOmTsPZdADmtVw 1 1 0 0   208b   208b
yellow open gw_test_registry_dataversion 9jpMxnsZQGWLNABGUvUPuw 1 1 1 0  3.1kb  3.1kb
```

Can you change the code to keep the same behaviour as before so we will keep the possibility to isolate each gateway datas on its proper indices group ?

Merci,

Regards,

**Comment by volkflo** [comment] 2021-08-18 09:01
Hi @OSMOSA44,

thanks for reporting this.
From your lines, I would assume that this is a bug.

We will try to have a look at it if we found time for this.
Any contributions, if you fix this would be appreciated.

**Comment by msavy** [comment] 2021-08-18 09:08
Is this not because the Elasticsearch client code was changed to have this prefix in 2.0.0 instead of allowing any name?

**Comment by volkflo** [comment] 2021-08-18 12:03
Yes, but I think it's only not taken correctly for the metrics.

If I understand it correctly `yellow open gw_test_metrics` will be created but then is writing metrics into `apiman_metrics`

**Comment by shachindrasingh** [comment] 2022-01-25 13:33
@volkflo ,
I had fix that issue .. please let me know how can i contribute that .

**Comment by volkflo** [comment] 2022-01-25 13:47
@shachindrasingh Sounds good, you can check out how to contribute in our readme.

Please see the steps here: https://github.com/apiman/apiman#contribute-fixes-and-features

**Comment by shachindrasingh** [comment] 2022-01-28 06:35
@volkflo Thanks,  i had follow all step that is mention in above URL . but while checkin some how getting error on workflow. can any one help me in that ..
my fork branch URL 
https://github.com/shachindrasingh/apiman.git

**Comment by volkflo** [comment] 2022-01-28 07:50
@shachindrasingh From the link you provided you can open a pull request directly.
See: 
![image](https://user-images.githubusercontent.com/13332383/151507803-e5cfc45c-0125-4b10-b737-e3f07474bcac.png)

**Comment by ncasaux** [comment] 2022-02-15 14:07
Hello @shachindrasingh,

Any chance that you could submit a PR for this feature ? I am also interested by this possibility to change the index name for metrics 😃

**Comment by msavy** [comment] 2022-02-15 14:12
Hi @ncasaux -- A PR is open from @shachindrasingh; but it needs some work before I can merge it onto master.

I'm currently very busy developing some cool new features that one of my customers needs, but I will get onto it as soon as I can. 

BTW, feel free to email me if you guys need something specific (email in profile).

**Comment by ncasaux** [comment] 2022-02-15 14:15
Hi @msavy 
Sorry I didn't see the PR...
Thanks for the update, I totally understand that it could require some rework.

**Comment by msavy** [comment] 2022-04-12 18:48
Fix hopefully on master now

**Comment by msavy** [comment] 2022-04-13 16:16
Please verify whether 2.2.1.Final works for you

**Comment by shachindrasingh** [comment] 2022-04-20 13:39
@msavy  sorry i haven't checked that on master due to some personal reason .. today i checked in latest release still issue was not complete resolved. i checked the code in latest release that is not my change . please use that change ..  other wise it will create the 3 different index .. eg.
magw_metrics_, magw_metrics, apiman_metrics


I had done very small change please use that one. other wise you need to do multiple changes in different files.

**Comment by msavy** [comment] 2022-04-20 13:49
> @msavy sorry i haven't checked that on master due to some personal reason .. today i checked in latest release still issue was not complete resolved. i checked the code in latest release that is not my change . please use that change .. other wise it will create the 3 different index .. eg. magw_metrics_, magw_metrics, apiman_metrics
> 
> I had done very small change please use that one. other wise you need to do multiple changes in different files.

The change I did is the same as yours, but didn't add in unnecessary additional methods.

I explained that in the pull request, please check it out.

Your original PR with my comments: https://github.com/apiman/apiman/pull/1778#issuecomment-1094282950
My refactoring of your PR to tidy it up: https://github.com/apiman/apiman/pull/1911

These should have the same effect

**Comment by msavy** [comment] 2022-04-20 14:05
OK, I think I can see the issue. This was caused by some refactoring that was contributed back in 2.0.0.Final.

I'll see what I can do to resolve it without causing any more problems.

**Closed** 2022-04-20 16:35 UTC
Labels: T: Bug
