### ISSUE TITLE
Docker installation out of date

### ISSUE THREAD

**Issue by thekevinm** [apiman/apiman#748] opened 2019-07-30 21:18 UTC
Following the Docker instructions found here: http://www.apiman.io/latest/download.html I was unable to install. Pulling down the image was fine `$ docker pull apiman/on-wildfly11:1.5.1.Final` but when running it `$ docker run -it -p 8080:8080 -p 8443:8443 apiman/on-wildfly11:1.5.1.Final` I got a mess.

```
21:06:36,167 ERROR [stderr] (ESRegistryCacheInvalidator) Exception in thread "ESRegistryCacheInvalidator" java.lang.RuntimeException: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:19200
21:06:36,168 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:76)
21:06:36,170 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createJestClient(DefaultESClientFactory.java:121)
21:06:36,175 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createClient(DefaultESClientFactory.java:68)
21:06:36,177 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.createClient(AbstractESComponent.java:61)
21:06:36,184 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.getClient(AbstractESComponent.java:51)
21:06:36,185 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry.checkCacheVersion(PollCachingESRegistry.java:204)
21:06:36,185 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry$6.run(PollCachingESRegistry.java:180)
21:06:36,185 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.lang.Thread.run(Thread.java:748)
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:19200
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:60)
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:65)
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 7 more
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
21:06:36,186 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
21:06:36,187 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
21:06:36,189 ERROR [stderr] (ESRegistryCacheInvalidator) Exception in thread "ESRegistryCacheInvalidator" 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
21:06:36,189 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
21:06:36,190 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
21:06:36,191 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
21:06:36,191 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
21:06:36,192 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
21:06:36,192 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
21:06:36,193 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
21:06:36,193 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:133)
21:06:36,195 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:67)
21:06:36,197 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 9 more
21:06:36,198 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: java.net.ConnectException: Connection refused (Connection refused)
21:06:36,200 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.PlainSocketImpl.socketConnect(Native Method)
21:06:36,200 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
21:06:36,201 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
21:06:36,201 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
21:06:36,202 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
21:06:36,202 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.Socket.connect(Socket.java:589)
21:06:36,203 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
21:06:36,203 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
21:06:36,205 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 20 more
21:06:36,206 ERROR [stderr] (ESRegistryCacheInvalidator) java.lang.RuntimeException: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:19200
21:06:36,207 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:76)
21:06:36,207 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createJestClient(DefaultESClientFactory.java:121)
21:06:36,208 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createClient(DefaultESClientFactory.java:68)
21:06:36,209 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.createClient(AbstractESComponent.java:61)
21:06:36,209 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.getClient(AbstractESComponent.java:51)
21:06:36,211 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry.checkCacheVersion(PollCachingESRegistry.java:204)
21:06:36,211 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry$6.run(PollCachingESRegistry.java:180)
21:06:36,212 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.lang.Thread.run(Thread.java:748)
21:06:36,215 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:19200
21:06:36,215 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)
21:06:36,218 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:60)
21:06:36,221 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:65)
21:06:36,221 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 7 more
21:06:36,223 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
21:06:36,223 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
21:06:36,224 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
21:06:36,224 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
21:06:36,226 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
21:06:36,226 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
21:06:36,232 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
21:06:36,234 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
21:06:36,234 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
21:06:36,235 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
21:06:36,237 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
21:06:36,238 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:133)
21:06:36,238 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:67)
21:06:36,239 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 9 more
21:06:36,239 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: java.net.ConnectException: Connection refused (Connection refused)
21:06:36,241 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.PlainSocketImpl.socketConnect(Native Method)
21:06:36,250 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
21:06:36,252 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
21:06:36,252 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
21:06:36,253 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
21:06:36,253 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.net.Socket.connect(Socket.java:589)
21:06:36,254 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
21:06:36,254 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
21:06:36,254 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 20 more
21:06:56,859 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 77) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./apiman-es: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./apiman-es: java.lang.RuntimeException: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:241)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:99)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	... 6 more
Caused by: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.waitForElasticToStart(ElasticServer.java:121)
	at pl.allegro.tech.embeddedelasticsearch.ElasticServer.start(ElasticServer.java:48)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.startElastic(EmbeddedElastic.java:73)
	at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:55)
	at io.apiman.common.es.util.ApimanEmbeddedElastic.start(ApimanEmbeddedElastic.java:90)
	at io.apiman.distro.es.Bootstrapper.contextInitialized(Bootstrapper.java:94)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:205)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
	... 8 more

21:06:56,885 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "apiman-es.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./apiman-es" => "java.lang.RuntimeException: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
    Caused by: java.lang.RuntimeException: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
    Caused by: pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out"}}
21:06:57,142 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 11.0.0.Final (WildFly Core 3.0.8.Final) started (with errors) in 73010ms - Started 1085 of 1432 services (2 services failed or missing dependencies, 647 services are lazy, passive or on-demand)
```

**Comment by EricWittmann** [comment] 2019-07-31 12:18
The all-in-one docker image tries to start up an embedded instance of elasticsearch.  It seems that ES didn't start up in a timely fashion, which caused all sorts of havoc.  I'm trying the latest on my centos box to see what I get.

**Comment by EricWittmann** [comment] 2019-07-31 12:21
Everything worked OK for me - what sort of docker host environment are you trying to run it in?

**Comment by volkflo** [comment] 2019-07-31 12:30
@EricWittmann This is mostly caused if the system is to slow.
The fix is this https://github.com/apiman/apiman/issues/721#issuecomment-475537916

Maybe we should add this timeout permanently to wait a little bit more

**Comment by EricWittmann** [comment] 2019-07-31 13:11
Closing as a duplicate of #721 - please feel free to continue the conversation there.

**Closed by EricWittmann** 2019-07-31 13:11 UTC
Labels: duplicate
